Don't run int. tests without write permission

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1,7 +1,10 @@
 name: Integration Tests
 
 on:
-  pull_request:
+  pull_request_target:
+    types:
+      - opened
+      - synchronize
   push:
     branches:
       - main
@@ -26,9 +29,28 @@ jobs:
       fail-fast: false
 
     steps:
-      - uses: actions/checkout@v4
-
-      - uses: ./.github/actions/install-pkg
+      - name: Fetch user permission
+        id: permission
+        uses: actions-cool/check-user-permission@v2
+        with:
+          require: write
+          username: ${{ github.triggering_actor }}
+      - name: Check user permission
+        if: steps.permission.outputs.require-result == 'false'
+        # If the triggering actor does not have write permission (i.e., this is a
+        # PR from a fork), then we exit, otherwise most of the integration tests will
+        # fail because they require access to secrets.  In this case, a maintainer
+        # will need to make sure the PR looks safe, and if so, manually re-run the
+        # failed actions.
+        run: |
+          echo "User ${{ github.triggering_actor }} does not have permission to run integration tests."
+          echo "Current permission level is ${{ steps.permission.outputs.user-permission }}."
+          echo "Job originally triggered by ${{ github.actor }}."
+          exit 1
+      - name: Checkout source
+        uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
       - name: Get full python version
